### ISSUE TITLE
Changes connection error handling

### ISSUE THREAD

**Issue by ngoossens** [go-kivik/couchdb#156]
The `Next` method for changes returns `io.EOF` even if the connection is interrupted (e.g. CouchDB is restarted/crashes). 

This is because the `More` method on `json.Decoder` returns false when the connection is closed, and therefore `Next` method returns `io.EOF`.

See: https://github.com/go-kivik/couchdb/blob/master/changes.go#L59
```golang
if !r.dec.More() {
	return io.EOF
}
```

So if you have a goroutine that calls `Next` in a loop the connection error will go unnoticed and you will not get any more changes. Ideally `Next` would return `io.ErrUnexpectedEOF` when the connection is interrupted.

**Comment by ngoossens** [comment]
Here is a simple application that reproduces this issue:

```golang
package main

import (
	"context"
	"fmt"
	_ "github.com/go-kivik/couchdb" // CouchDB Driver for kivik
	"github.com/go-kivik/kivik"
)

func main() {
	cdb, err := kivik.New("couch", "http://admin:password@localhost:5984/")
	if err != nil {
		panic(err)
	}

	db := cdb.DB(context.TODO(), "mydatabase")
	if db.Err() != nil {
		panic(db.Err())
	}

	changes, err := db.Changes(context.TODO())
	if err != nil {
		panic(err)
	}

	fmt.Println("Connected to change feed. Please shutdown CouchDB to demonstrate the bug.")
	fmt.Println("Documents changed:")

	for {
		if !changes.Next() {
			if changes.Err() != nil {
				break
			}
		}

		fmt.Println(changes.ID())
	}
	
	fmt.Println("This will never be printed!")
}
```

**Comment by flimzy** [comment]
Thank you for the error report, and the reproduction case. It's not immediately obvious to me how to fix it, but I'll work on it when I have time (hopefully this weekend). In the meantime, if you find a solution, a PR is always appreciated.

**Comment by ngoossens** [comment]
Thanks for looking into the issue as well as providing a great library!

Both `More` and `Decode` on `json.Decoder` are blocking so my initial idea was to remove the `More` call and add a special case to handle the `io.EOF` error. I am not certain on the full implication of this change though so was hesitant to do a PR.

The changed method would look something like this:
```
func (r *changesRows) Next(row *driver.Change) error {
	if r.dec == nil {
		r.dec = json.NewDecoder(r.body)
	}

	if err := r.dec.Decode(row); err != nil {
		if err == io.EOF {
			return io.EOF
		}

		return &kivik.Error{HTTPStatus: http.StatusBadGateway, Err: err}
	}
	return nil
}
```

**Comment by flimzy** [comment]
I did a little experimentation with just using `Decode()`. That is promising, but there's a problem that it still seems to lose any read error, if the read error occurs at the end of a valid JSON object (which will be the typical case).

So I see two issues here:
1. `Next()` should not continue forever (as you observe). This is probably the easier of the two problems to fix.
2. Read errors should be returned to the caller.  I don't see an obvious way to handle this, based on my superficial testing thus far. But I should have more time to dig in tomorrow, and hopefully find something.

**Comment by flimzy** [comment]
I believe I've found a solution. Stand by. :)

**Comment by flimzy** [comment]
Please let me know if this solves your problem.

**Comment by ngoossens** [comment]
That solves the issue :) Thanks for the amazingly quick fix!
