### ISSUE TITLE
Provide example of DSN in docs

### ISSUE THREAD

**Issue by xiegeo** [go-kivik/couchdb#164]
In the documentation: https://godoc.org/github.com/go-kivik/couchdb#hdr-Authentication
`For most uses, you don't need to worry about authentication at all--just include authentication credentials in your connection DSN. This will use Cookie authentication by default. `

This is nice, but an example of DSN or where to look up this information is not provided.

**Comment by flimzy** [comment]
It uses standard URL notation for authentication credentials, but I can add that to the docs.
