### ISSUE TITLE
Should set the http request header "Accept"  by Get() method

### ISSUE THREAD

**Issue by silencily** [go-kivik/couchdb#185]
File db.go 

    func (d *db) get(ctx context.Context, method string, docID string, options map[string]interface{}) (*http.Response, string, error) {
    	if docID == "" {
    		return nil, "", missingArg("docID")
    	}
    	inm, err := ifNoneMatch(options)
    	if err != nil {
    		return nil, "", err
    	}
    	params, err := optionsToParams(options)
    	if err != nil {
    		return nil, "", err
    	}
    	opts := &chttp.Options{
    		Accept:      typeJSON,
    		IfNoneMatch: inm,
    		Query:       params,
    	}
    	resp, err := d.Client.DoReq(ctx, method, d.path(chttp.EncodeDocID(docID)), opts)
    	if err != nil {
    		return nil, "", err
    	}
    	if respErr := chttp.ResponseError(resp); respErr != nil {
    		return nil, "", respErr
    	}
    	rev, err := chttp.GetRev(resp)
    	return resp, rev, err
    }

The method has a problem , this request header "Accept" is "application/json" always.
So, the server's response 'content-type' can't be "multipart/related" , and method "GET()" never can execute the branch `case typeMPRelated:` . The result of return never contain the "Attachments" even if set opts "attachments=true".

PS: Sorry about my English, hope U can understand ^.^

**Comment by flimzy** [comment]
Thanks for reporting the issue. It should be fixed now. Please let me know if you have any problems with this feature.
