### ISSUE TITLE
Changes options not effecting output

### ISSUE THREAD

**Issue by jspspike** [go-kivik/couchdb#195]
I'm trying to filter changes feed by document but it does not seem to work. Not sure if I'm using this improperly or there's actually a problem.
This is how I request the changes.
```golang
options := make(map[string]interface{})
options["doc_ids"] = []string{doc.docId}
changes, err := doc.db.Changes(context.TODO(), options)
```
When iterating through these using `Next()` I seem to have every document in this database. Is this maybe because the url doesn't have the argument `?filter=_doc_ids` as shown on the [couch documentation](https://couchdb.readthedocs.io/en/latest/api/database/changes.html#get--db-_changes).

**Comment by flimzy** [comment]
Which version of Kivik are you using?

**Comment by jspspike** [comment]
I'm using 2.0.0-pre

**Comment by flimzy** [comment]
I've been using the changes feed with `doc_id` filters on master for several weeks. I've just tagged `2.0.0-pre2` with the latest changes. Would you try that, and see if it works? If not, I'll need to see a more complete reproduction case to debug the problem.

Thanks.

**Comment by jspspike** [comment]
So updated to the new release but it still doesn't work. Not sure how much more context I can give you.

Here's all the changes by manually curling `curl localhost:5984/configuration/_changes`
```
{"results":[
{"seq":105,"id":"DGA","------":[{"rev":"1-1dee8c178faee4946a86cc5ca8c63601"}]},
{"seq":106,"id":"------","changes":[{"rev":"1-b52416a7ace385c45148c69475fa38c6"}]},
{"seq":109,"id":"------","changes":[{"rev":"1-50f93572408005472c6770f33546e94c"}]},
{"seq":111,"id":"------","changes":[{"rev":"1-f694784c83985f8880c1e397833c601d"}]},
{"seq":112,"id":"------","changes":[{"rev":"1-4e10ff87aa64ca0d4ab3385516af0446"}]},
{"seq":113,"id":"------","changes":[{"rev":"1-39a982d377adfbe43db4144189ef3f34"}]},
{"seq":115,"id":"------","changes":[{"rev":"1-8c82f00884164ae301cc9c250f7db5b9"}]},
...
{"seq":2770,"id":"------","changes":[{"rev":"18-e65862dfe351a7a731349391019890f0"}]},
{"seq":2771,"id":"------","changes":[{"rev":"18-37e170f102c1f3ae14e621beb0b2edb6"}]},
{"seq":2772,"id":"------","changes":[{"rev":"18-24a435b902cb883cc22f567797bc45ef"}]},
{"seq":2773,"id":"------","changes":[{"rev":"25-2a49057e5c0d5a2b583aaec44927d24a"}]},
{"seq":2774,"id":"------","changes":[{"rev":"25-de151c4f98a12544400a88e60bd85f20"}]},
{"seq":2775,"id":"------","changes":[{"rev":"23-e821d5da21b6db96becb3a19796579f7"}]},
{"seq":2776,"id":"------","changes":[{"rev":"23-89c79c3af60aea6a969dc9104e2c6623"}]},
{"seq":2777,"id":"------","changes":[{"rev":"17-c26933ac92cf4135bf8ed6436c0c5a1c"}]},
{"seq":2778,"id":"------","changes":[{"rev":"21-c6a981740ac4f9c674513f7091cd88bc"}]},
{"seq":2779,"id":"------","changes":[{"rev":"44-24444fdfb39713c784fe7234f8656283"}]},
{"seq":2780,"id":"------","changes":[{"rev":"44-ac5c5ed0e188b63da9fb717c6103ebe0"}]},
{"seq":2781,"id":------","changes":[{"rev":"43-0cfd491c1905775b8706827d0e1fc91d"}]},
{"seq":2809,"id":"------","changes":[{"rev":"18-276b74f14c9f4ea385318f21c53a9255"}]},
{"seq":2810,"id":"host-context-learning","changes":[{"rev":"4-ddda97604c1279aefcad635a71a5f273"}]},
{"seq":2849,"id":"------","changes":[{"rev":"222-dfca4c5d7f225152dcc585e4f14c7a0d"}]}
],
"last_seq":2849}
```

If I curl using the filter it filters fine `curl localhost:5984/configuration/_changes?filter=_doc_ids -X POST -H "Content-Type: application/json" -d '{"doc_ids": ["host-context-learning"]}'`
```
{"results":[
{"seq":2810,"id":"host-context-learning","changes":[{"rev":"4-ddda97604c1279aefcad635a71a5f273"}]}
],
"last_seq":2849}
```

Here's some more of the code I use when attempting to do this in go.
```golang
options := make(map[string]interface{})
options["doc_ids"] = []string{doc.docId}
log.WithFields(logrus.Fields{
     "options": options,
}).Warn("Options print")
changes, err := doc.db.Changes(context.TODO(), options)
if err != nil {
	doc.errLog(err).Error("Failed to get changes feed from db")
}

changeTicker := time.NewTicker(checkInterval)

//seq_checkpoint := ""

for {
	select {
	case <-changeTicker.C:
		for changes.Next() {
			seq := changes.Seq()
			println(seq)
		}
	}
}
```

Resulting output:
```
WARN Options print                                 options="map[doc_ids:[host-context-learning]]"
...
105
106
109
111
112
113
115
116
117
118
120
121
122
123
124
125
126
130
131
132
133
134
137
138
139
141
142
143
144
145
146
147
148
149
151
152
153
154
155
156
157
158
160
161
...
2764
2765
2766
2767
2768
2769
2770
2771
2772
2773
2774
2775
2776
2777
2778
2779
2780
2781
2809
2810
2849
```

This still prints out the sequence number for every change

**Comment by flimzy** [comment]
If you add:

    options["filter"] = "_doc_ids"

does it work?

**Comment by jspspike** [comment]
This gives me a `Bad Request: invalid_json` error when calling `Changes`

**Comment by flimzy** [comment]
I'll try to debug this when I have time.  If you could provide a minimal, reproduction case (i.e. a single `.go` file that I can run, to demonstrate the problem), it would probably make it easier for me to get to that sooner.

**Comment by jspspike** [comment]
So after a little debugging I figured out the issue. Turns out that the function `optionsToParams` found [here](../blob/master/db.go#L45) will take represent a string and an array of strings the same. This means in the resulting URI instead of having `?doc_ids=["nameofdoc"]` we get `?doc_ids=nameofdoc` and gets the invalid_json error. I could make a PR changing how optionsToParams works but I'm not sure if other things depend on this behavior

**Comment by flimzy** [comment]
Ah, nice find.
The solution is probably just to add `doc_ids` to [this list of query params to be JSON-encoded](https://github.com/go-kivik/couchdb/blob/master/json.go#L22).

It's a bit hacky, but I think that's the quickest way to solve the problem. If it's easy for you to test that, would you let me know if that works?

**Comment by jspspike** [comment]
That works, made a small PR with the change
