### ISSUE TITLE
The v3.0.1 release is not usable

### ISSUE THREAD

**Issue by nono** [go-kivik/couchdb#232]
Hello, it looks like the v3.0.1 release was made from a branch where work for the v4 was started: https://github.com/go-kivik/couchdb/blob/v3.0.1/go.mod. When trying to install this release, the go tools say:

```
go: github.com/go-kivik/couchdb/v3@v3.0.1: go.mod has non-.../v3 module path "github.com/go-kivik/couchdb/v4" (and .../v3/go.mod does not exist) at revision v3.0.1
```

**Comment by flimzy** [comment]
Thank you for the bug report. That was an obvious tagging error!  I've tagged v3.0.2 to fix this.  https://github.com/go-kivik/couchdb/releases/tag/v3.0.2

**Comment by nono** [comment]
Thanks :heart:
