### ISSUE TITLE
Add the ability to authenticate with a raw access token

### ISSUE THREAD

**Issue by flimzy** [go-kivik/couchdb#8]
Requested [here](https://github.com/flimzy/kivik/issues/199#issuecomment-331148992):

> > Additions to 3.) It will be good when there something like this for authentication with an token:
>
> An auth method that takes a raw cookie value is not a bad idea, and probably not difficult to implement. I'll try to do that, too. Thanks for the suggestion.

@SerkanSipahi [suggests](https://github.com/flimzy/kivik/issues/199#issuecomment-331439791) calling it `chttp.TokenAuth`.

**Comment by SerkanSipahi** [comment]
@flimzy that's not implemented (`chttp.TokenAuth`) anymore?

**Comment by SerkanSipahi** [comment]
I'm sorry I misread the issue. The issue is still active :)

**Comment by flimzy** [comment]
I have added similar support with https://github.com/go-kivik/couchdb/pull/142

**Comment by SerkanSipahi** [comment]
@flimzy thank you, will check!
